
from pydantic import BaseModel, EmailStr, Field, constr
from typing import Optional, Annotated
from datetime import datetime

class GSTRegistrationIn(BaseModel):
    customer_id: int = Field(..., description="Customer ID")
    username: str = Field(..., description="Username")
    password: str = Field(..., description="Password")
    pan: Annotated[str, Field(pattern=r'^[A-Z]{5}[0-9]{4}[A-Z]$')] = Field(..., description="PAN must be 10 characters (5 letters, 4 digits, 1 letter)")
    registration_type: Optional[str] = Field(None, description="Registration type (NORMAL / COMPOSITION)")
    ownership_category: Optional[str] = Field(None, description="Ownership category")
    business_type: Optional[str] = Field(None, description="Business type")
    state: Optional[str] = Field(None, description="State")
    turnover_details: Optional[str] = Field(None, description="Turnover details (LESS_THAN_2CR / LESS_THAN_5CR / MORE_THAN_5CR)")
    created_by: Optional[int] = Field(None, description="Created by OP ID")
    rm_id: Optional[int] = Field(None, description="RM ID")
    gstin: Optional[Annotated[str, Field(pattern=r'^[0-9A-Z]{15}$')]] = Field(None, description="GSTIN must be exactly 15 alphanumeric characters")
    is_filing_needed: Optional[bool] = Field(True, description="Is filing needed")
    mobile: Annotated[str, Field(pattern=r'^\d{10}$')] = Field(None, description="Phone number must be exactly 10 digits")
    is_active: Optional[bool] = Field(True, description="Is active")
    email: Optional[EmailStr] = Field(None, description="Email address")
    secondary_email: Optional[EmailStr] = Field(None, description="Secondary email address")

class GSTRegistrationEditIn(BaseModel):
    gstin: Optional[Annotated[str, Field(pattern=r'^[0-9A-Z]{15}$')]] = Field(None, description="GSTIN must be exactly 15 alphanumeric characters")
    username: Optional[str] = Field(None, description="Username")
    password: Optional[str] = Field(None, description="Password")
    pan: Optional[Annotated[str, Field(pattern=r'^[A-Z]{5}[0-9]{4}[A-Z]$')]] = Field(None, description="PAN must be 10 characters (5 letters, 4 digits, 1 letter)")
    registration_type: Optional[str] = Field(None, description="Registration type")
    ownership_category: Optional[str] = Field(None, description="Ownership category")
    business_type: Optional[str] = Field(None, description="Business type")
    state: Optional[str] = Field(None, description="State")
    turnover_details: Optional[str] = Field(None, description="Turnover details")
    registration_status: Optional[str] = Field(None, description="Registration status")
    suspension_reason: Optional[str] = Field(None, description="Suspension reason")
    cancellation_reason: Optional[str] = Field(None, description="Cancellation reason")
    approved_at: Optional[datetime] = Field(None, description="Approved at timestamp")
    is_rcm_applicable: Optional[bool] = Field(None, description="Is RCM applicable")
    is_filing_needed: Optional[bool] = Field(True, description="Is filing needed")
    mobile: Annotated[str, Field(pattern=r'^\d{10}$')] = Field(None, description="Phone number must be exactly 10 digits")
    is_active: Optional[bool] = Field(None, description="Is active")
    email: Optional[EmailStr] = Field(None, description="Email address")
    secondary_email: Optional[EmailStr] = Field(None, description="Secondary email address")
    rm_id: Optional[int] = Field(None, description="RM ID")

class GSTRegistrationOut(BaseModel):
    id: int = Field(..., description="ID")
    customer_id: int = Field(..., description="Customer ID")
    gstin: Optional[Annotated[str, Field(pattern=r'^[0-9A-Z]{15}$')]] = Field(None, description="GSTIN")
    username: str = Field(..., description="Username")
    is_active: bool = Field(..., description="Is active")
    email: Optional[EmailStr] = Field(None, description="Email address")
    secondary_email: Optional[EmailStr] = Field(None, description="Secondary email address")
    pan: Annotated[str, Field(pattern=r'^[A-Z]{5}[0-9]{4}[A-Z]$')] = Field(..., description="PAN")
    registration_type: Optional[str] = Field(None, description="Registration type")
    ownership_category: Optional[str] = Field(None, description="Ownership category")
    business_type: Optional[str] = Field(None, description="Business type")
    state: Optional[str] = Field(None, description="State")
    turnover_details: Optional[str] = Field(None, description="Turnover details")
    registration_status: Optional[str] = Field(None, description="Registration status")
    suspension_reason: Optional[str] = Field(None, description="Suspension reason")
    cancellation_reason: Optional[str] = Field(None, description="Cancellation reason")
    approved_at: Optional[datetime] = Field(None, description="Approved at")
    is_rcm_applicable: bool = Field(..., description="Is RCM applicable")
    created_by: Optional[int] = Field(None, description="Created by")
    is_filing_needed: bool = Field(..., description="Is filing needed")
    created_at: datetime = Field(..., description="Created at")
    updated_at: datetime = Field(..., description="Updated at")
    message: Optional[str] = Field(None, description="Message")
    rm_id: Optional[int] = Field(None, description="RM ID")

class RegistrationPersonIn(BaseModel):
    customer_id: Optional[int] = Field(None, description="Customer ID")
    gstin: Annotated[str, Field(pattern=r'^[0-9A-Z]{15}$')] = Field(..., description="GSTIN")
    full_name: str = Field(..., description="Full name")
    role: str = Field(..., description="Role")
    pan: Optional[Annotated[str, Field(pattern=r'^[A-Z]{5}[0-9]{4}[A-Z]$')]] = Field(None, description="PAN")
    aadhaar: Optional[Annotated[str, Field(pattern=r'^\d{12}$')]] = Field(None, description="Aadhaar must be exactly 12 digits")
    email: Optional[EmailStr] = Field(None, description="Email address")
    mobile: Optional[Annotated[str, Field(pattern=r'^\d{10}$')]] = Field(None, description="Mobile number must be exactly 10 digits")
    is_primary_customer: Optional[bool] = Field(False, description="Is primary customer")

class RegistrationPersonEditIn(BaseModel):
    full_name: Optional[str] = Field(None, description="Full name")
    role: Optional[str] = Field(None, description="Role")
    pan: Optional[Annotated[str, Field(pattern=r'^[A-Z]{5}[0-9]{4}[A-Z]$')]] = Field(None, description="PAN")
    aadhaar: Optional[Annotated[str, Field(pattern=r'^\d{12}$')]] = Field(None, description="Aadhaar must be exactly 12 digits")
    email: Optional[EmailStr] = Field(None, description="Email address")
    mobile: Optional[Annotated[str, Field(pattern=r'^\d{10}$')]] = Field(None, description="Mobile number must be exactly 10 digits")
    is_primary_customer: Optional[bool] = Field(None, description="Is primary customer")

class RegistrationPersonOut(BaseModel):
    person_id: int = Field(..., description="Person ID")
    customer_id: Optional[int] = Field(None, description="Customer ID")
    gstin: str = Field(..., description="GSTIN")
    full_name: str = Field(..., description="Full name")
    role: str = Field(..., description="Role")
    pan: Optional[str] = Field(None, description="PAN")
    aadhaar: Optional[str] = Field(None, description="Aadhaar")
    email: Optional[EmailStr] = Field(None, description="Email address")
    mobile: Optional[str] = Field(None, description="Mobile number")
    is_primary_customer: Optional[bool] = Field(False, description="Is primary customer")
    message: Optional[str] = Field(None, description="Message")

class RegistrationDocumentIn(BaseModel):
    gstin: Annotated[str, Field(pattern=r'^[0-9A-Z]{15}$')] = Field(..., description="GSTIN")
    person_id: Optional[int] = Field(None, description="Person ID")
    document_type: str = Field(..., description="Document type")
    document_url: str = Field(..., description="Document URL")
    ownership_category: Optional[str] = Field(None, description="Ownership category")
    mobile: Optional[Annotated[str, Field(pattern=r'^\d{10}$')]] = Field(None, description="Mobile number")

class RegistrationDocumentEditIn(BaseModel):
    document_type: Optional[str] = Field(None, description="Document type")
    document_url: Optional[str] = Field(None, description="Document URL")
    ownership_category: Optional[str] = Field(None, description="Ownership category")
    verified: Optional[bool] = Field(None, description="Is verified")
    verified_by: Optional[int] = Field(None, description="Verified by user ID")
    verified_at: Optional[datetime] = Field(None, description="Verified at timestamp")
    mobile: Optional[Annotated[str, Field(pattern=r'^\d{10}$')]] = Field(None, description="Mobile number")
    
class RegistrationDocumentOut(BaseModel):
    document_id: int = Field(..., description="Document ID")
    gstin: str = Field(..., description="GSTIN")
    person_id: Optional[int] = Field(None, description="Person ID")
    document_type: str = Field(..., description="Document type")
    document_url: str = Field(..., description="Document URL")
    ownership_category: Optional[str] = Field(None, description="Ownership category")
    verified: Optional[bool] = Field(None, description="Is verified")
    verified_by: Optional[int] = Field(None, description="Verified by user ID")
    verified_at: Optional[datetime] = Field(None, description="Verified at timestamp")
    uploaded_at: Optional[datetime] = Field(None, description="Uploaded at timestamp")
    mobile: Optional[str] = Field(None, description="Mobile number")
