"""Shared constants for GST registration CRM push / intake."""

GST_CRM_ENTITY_TYPE = "GST_REGISTRATION"
CRM_LEAD_STAGE_PENDING_REGISTRATION_DATA = "PENDING_REGISTRATION_DATA"

# Minimal defaults for CRM push (draft row; staff complete details later).
DEFAULT_GST_INTAKE_REGISTRATION_TYPE = "REGULAR"
DEFAULT_GST_INTAKE_OWNERSHIP_CATEGORY = "INDIVIDUAL"
DEFAULT_GST_INTAKE_TURNOVER_DETAILS = "LESS_THAN_2CR"
